---
# neo4j

- name: Add neo4j repo
  shell: |
    wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
    echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
    sudo apt-get update    

- name: Install Packages
  apt: 
    name:
      - neo4j=1:3.5.12
    state: present
    autoclean: yes      
  become: yes
  become_user: root
  become_method: sudo

- name: Download neosemantics
  get_url:
    url: "https://github.com/neo4j-labs/neosemantics/releases/download/3.5.0.4/neosemantics-3.5.0.4.jar"
    dest: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: /var/lib/neo4j/plugins
    owner: neo4j
    group: adm
    mode: 0755
    remote_src: yes
  become: yes
  become_user: root
  become_method: sudo       
  notify: restart neo4j
  when: 
    - skip_download is not defined   

- name: Copy neo4j.conf to /etc/neo4j/
  copy:
    src: files/neo4j.conf
    dest: /etc/neo4j/neo4j.conf
    owner: neo4j
    group: adm
    mode: 0640
  notify: restart neo4j

- name: Enable and start neo4j service
  service:
    name: neo4j
    state: started
    enabled: yes

- name: Copy Neo4j service definition
  copy:
    src: files/neo4j.tpl
    dest: /etc/consul.d/neo4j.tpl
    owner: consul
    group: consul
    mode: 0755
    
- name: Update Neo4j bind address and restart consul to register Neo4j as a service
  shell: |
    set -e
    cd /etc/consul.d/
    bind_addr=$(ifconfig | grep eth1 -A 1 | grep inet | awk '{ print $2 }')
    cat neo4j.tpl | sed 's/__ip__/'"${bind_addr}"'/g' > neo4j.json
    chown consul:consul neo4j.json
    /usr/local/bin/consul reload
    exit 0    

