---

# -------------------------------------------------------------------------------------
# registry
# -------------------------------------------------------------------------------------
- name: registry
  hosts: "{{ target_hosts }}" 
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars:
    host_url: "{{host_url}}" 
    consul_version: "1.9.0"
    consul_nodes: 
      - "{{consul_node1}}"
      - "{{consul_node2}}"
      - "{{consul_node3}}"    
  roles:
    - role: consul-agent
    - role: docker-registry
