---
# Install Password

# Setup/install tasks.

- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}_{{ ansible_architecture }}.yml"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'