---

# -------------------------------------------------------------------------------------
# Prometheus
# -------------------------------------------------------------------------------------
- name: prometheus
  hosts: nodes
  become: true
  become_user: root
  become_method: sudo  
  vars:
    consul_version: "1.9.0"
    consul_nodes: 
      - "tmt-vm1.7onetella.net"
      - "tmt-vm2.7onetella.net"
      - "tmt-vm3.7onetella.net"    
    version: "2.14.0"
    targets:
      - "localhost:9090"
      - "192.168.0.107:9100"
      - "192.168.0.108:9100" 
  roles:
    - role: consul-agent
      when: setup_option == 'consul'
    - role: prometheus