---

# -------------------------------------------------------------------------------------
# Nomad
# -------------------------------------------------------------------------------------
- name: nomad
  hosts: "{{ target_hosts }}"
  user: "{{ ansible_user }}"
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars: 
    consul_version: "1.9.0"
    nomad_version: "1.0.0"
    consul_nodes: 
      - "{{consul_node1}}"
      - "{{consul_node2}}"
      - "{{consul_node3}}"    
    nomad_nodes: 
      - "{{node1}}"
      - "{{node2}}"
      - "{{node3}}"
  roles:
    - role: consul-agent
    - role: nomad-cluster