---

# -------------------------------------------------------------------------------------
# Proxmox node setup
# -------------------------------------------------------------------------------------
- name: proxmox
  hosts: nodes
  user: "{{ ansible_user }}"
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  roles:
    - role: proxmox-base
