---

- name: Install Grafana deb package 
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_8.4.3_amd64.deb     

- name: Copy grafana.ini
  copy:
    src: files/grafana.ini
    dest: "/etc/grafana"
    owner: "grafana"
    group: "grafana"
    mode: 0640    
  notify: restart grafana

- name: Copy Grafana service definition
  copy:
    src: files/grafana-server
    dest: /etc/default/grafana-server
    owner: root
    group: root
    mode: 0644

- name: Enable and start grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes      
