---
# Install Jupyter Lab

- name: Install Packages
  apt: 
    name:
      - uuid
    state: present
    autoclean: yes      
  become: yes
  become_user: root
  become_method: sudo

- name: Install Python dependencies
  pip: 
    name: 
      - jupyterlab
    extra_args: --user
    state: latest
  become: true
  become_user: "{{ user }}"

- name: Create .jupyter folder
  file:
    path: "/home/{{ user }}/.jupyter"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Copy password configuration file
  copy:
    src: files/jupyter_notebook_config.json
    dest: /home/vagrant/.jupyter/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Copy startup script
  template:
    src: jupyterlab.sh.j2
    dest: /usr/local/bin/jupyterlab.sh
    owner: root
    group: root
    mode: 0755

- name: Copy service script
  copy:
    src: files/jupyterlab.service
    dest: /etc/systemd/system/jupyterlab.service
    owner: root
    group: root
    mode: 0644

- name: Enable and start jupyterlab service
  service:
    name: jupyterlab
    state: started
    enabled: yes        

- name: Copy Jupyter Lab service definition
  copy:
    src: files/jupyterlab.tpl
    dest: /etc/consul.d/jupyterlab.tpl
    owner: consul
    group: consul
    mode: 0755

- name: Copy register.sh
  copy:
    src: files/register.sh
    dest: /etc/consul.d/register.sh
    owner: consul
    group: consul
    mode: 0755
  become: yes
  become_user: root
  become_method: sudo

- name: Register Jupyter Lab with Consul
  shell: |
    set -e
    /etc/consul.d/register.sh
    exit 0    
  become: yes
  become_user: root
  become_method: sudo
