---

- name: Install pgAdmin using apt install 
  shell: |
    curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add
    sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
    apt install -y pgadmin4-web 
    exit 0
  register: output

- name: Capture install output
  debug:
    var: output.stdout_lines
