---
# Install Go

- name: Delete previous install
  file:
    path: /usr/local/go
    state: absent
  become: yes
  become_user: root
  become_method: sudo       
  when: 
    - skip_download is not defined

- name: Download Go for Debian
  unarchive:
    src: https://dl.google.com/go/go{{ version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes
  become_user: root
  become_method: sudo       
  when: 
    - skip_download is not defined

- name: set home 
  set_fact:
    home: "/root"
  when: user == "root"

- name: set home 
  set_fact:
    home: "/var/lib/jenkins"
  when: user == "jenkins"

- name: set home 
  set_fact:
    home: "/home/{{ user }}"
  when: user != "root" and user != "jenkins"

- name: Copy .zshrc to user home
  template:
    src: .zshrc.j2
    dest: "{{ home }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0640  
