---
# Install Docker Registry 

# Setup/install tasks.

- include_tasks: setup-with-consul.yml
  when: setup_option == 'consul'

- include_tasks: setup-with-noconsul.yml
  when: setup_option == 'noconsul'