---

# -------------------------------------------------------------------------------------
# registry
# -------------------------------------------------------------------------------------
- name: registry
  hosts: nodes 
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars:
    host_url: "{{ host_url }}" 
    version: "{{ version }}"
  roles:
    - role: docker-registry
