---

- name: Simple Example
  hosts: nodes
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.14.0
    es_config:
      http.host: 0.0.0.0
    es_api_basic_auth_username: es_admin
    es_api_basic_auth_password: changeMe  
    es_users:
      file:
        es_admin:
          password: changeMe
          roles:
            - admin
        logstash:
          password: changeMe
          roles:
            - logstash
        foo:
          password: changeMe
          roles:
            - power_user
    es_roles:
      file:
        admin:
          cluster:
            - all
          indices:
            - names: '*'
              privileges:
                - all
        power_user:
          cluster:
            - all
          indices:
            - names: '*'
              privileges:
                - all                
        logstash:
          cluster:
            - all
          indices:
            - names: 'logstash-*'
              privileges:
                - all
  