---

- name: filebrowser 
  hosts: nodes
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars: 
    root_dir: "{{ root_dir }}"
    admin_password: "{{ admin_password }}"
    nfs_host: "{{ nfs_host }}"    
    mount_path: "{{ mount_path }}"
  roles:
    - filebrowser