---

- name: Fluentd
  hosts: nodes
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true  
  vars:
    fluentd_version: 4
    fluentd_package_state: latest
    fluentd_service_name: td-agent
    fluentd_service_state: started
    fluentd_service_enabled: true
    fluentd_conf_sources: |
      <match nginx.access>
        @type elasticsearch
        @id access_log
        host 192.168.69.117
        port 9200
        logstash_format true
        <buffer>
          flush_mode immediate
        </buffer>
        user logstash
        password changeMe        
      </match>
      <source>
        @type tail
        @id input_tail
        path /var/log/nginx/access.log
        pos_file /var/log/td-agent/tmp/access.log.pos
        <parse>
          @type nginx
          keep_time_key true
        </parse>
        tag nginx.access
      </source>
  roles:
    - fluentd
    - geerlingguy.fluentd
