---

# -------------------------------------------------------------------------------------
# initializes instance 
# -------------------------------------------------------------------------------------
- name: set hostname, apt update, apt upgrade
  hosts: default
  serial: "{{ serial_size | default(1) }}"
# serial: 1 means rolling update. that helps to eliminate the time outs on slow computer
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  user: "{{ user }}"
  tasks:
    - apt:
        update_cache: yes        
        upgrade: yes
    - apt:
        name:
          - python3-pip
        state: present
        autoclean: yes
  roles:
    - role: oh-my-zsh