---

# -------------------------------------------------------------------------------------
# Golang
# -------------------------------------------------------------------------------------
- name: go
  hosts: nodes 
  become: true
  become_user: root
  become_method: sudo  
  vars: 
    user: "{{ username }}"
    version: "{{ version }}"
  roles:
    - role: go