---

# -------------------------------------------------------------------------------------
# Golang
# -------------------------------------------------------------------------------------
- name: go
  hosts: "{{ target }}"
  vars: 
    version: "1.14.4"
  user: "{{ user }}"
  roles:
    - role: go