---

# -------------------------------------------------------------------------------------
# Grafana
# -------------------------------------------------------------------------------------
- name: grafana
  hosts: nodes
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  roles:
    - role: grafana