---

# -------------------------------------------------------------------------------------
# Graphite
# -------------------------------------------------------------------------------------
- name: graphite
  hosts: "{{ target }}"
  user: "{{ user }}"
  roles:
  - role: graphite