---

# -------------------------------------------------------------------------------------
# Jupyter Lab
# -------------------------------------------------------------------------------------
- name: jupyterlab
  hosts: nodes
  become: true
  become_user: root
  become_method: sudo  
  vars:
    consul_version: "1.9.0"
    consul_nodes: 
      - "tmt-vm1.7onetella.net"
      - "tmt-vm2.7onetella.net"
      - "tmt-vm3.7onetella.net"
    bind_addr: "{{ bind_addr }}"    
    setup_option: "{{ setup_option }}"
  roles:
    - role: consul-agent
      when: setup_option == 'consul'  
    - role: jupyterlab

# password is password