---

# -------------------------------------------------------------------------------------
# Jupyter Lab
# -------------------------------------------------------------------------------------
- name: jupyterlab
  hosts: "{{ target }}"
  user: "{{ user }}"
  become: true
  become_user: root
  become_method: sudo  
  vars:
    consul_version: "1.9.0"
    consul_nodes: 
      - "tmt-vm1.7onetella.net"
      - "tmt-vm2.7onetella.net"
      - "tmt-vm3.7onetella.net"    
  roles:
    - consul-agent  
    - jupyterlab

# password is password