---

# -------------------------------------------------------------------------------------
# Neo4j
# -------------------------------------------------------------------------------------
- name: neo4j
  hosts: "{{ target }}"
  serial: "{{ serial_size | default(1) }}"  
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  roles:
    - neo4j