---

# -------------------------------------------------------------------------------------
# Projector
# -------------------------------------------------------------------------------------
- name: projector
  hosts: nodes 
  become: true
  become_user: root
  become_method: sudo  
  vars: 
    ide: "{{ ide }}"
    config_name: "{{ config_name }}"
    port: "{{ port }}"
    username: "debian"
  roles:
    - role: projector