---

- name: promtail
  hosts: nodes
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars: 
    loki_host: "{{ loki_host }}"
    version: "2.4.2"
    job_label: "{{ job_label }}"
    log_path_expression: "{{ log_path_expression }}"
  roles:
    - promtail