---

# -------------------------------------------------------------------------------------
# Prometheus
# -------------------------------------------------------------------------------------
- name: prometheus
  hosts: "{{ target }}"
  user: "{{ user }}"
  become: true
  become_user: root
  become_method: sudo  
  vars:
    consul_version: "1.9.0"
    consul_nodes: 
      - "tmt-vm1.7onetella.net"
      - "tmt-vm2.7onetella.net"
      - "tmt-vm3.7onetella.net"    
    version: "2.14.0"
  roles:
    - consul-agent
    - prometheus