---

# -------------------------------------------------------------------------------------
# Prometheus
# -------------------------------------------------------------------------------------
- name: prometheus
  hosts: nodes
  become: true
  become_user: root
  become_method: sudo  
  vars:
    version: "2.14.0"
    targets:
      - "192.168.4.100:9100"
      - "192.168.4.101:9100"
      - "192.168.4.104:9100" 
      - "192.168.4.130:9100"
    nginx: "192.168.4.100:9113"
  roles:
    - role: prometheus
