---

# -------------------------------------------------------------------------------------
# Prometheus
# -------------------------------------------------------------------------------------
- name: prometheus
  hosts: nodes
  become: true
  become_user: root
  become_method: sudo  
  vars:
    version: "2.14.0"
    targets:
      - "192.168.69.100:9100"
      - "192.168.69.101:9100"
      - "192.168.69.104:9100" 
  roles:
    - role: prometheus
