---

# -------------------------------------------------------------------------------------
# Redis
# -------------------------------------------------------------------------------------
- name: Redis
  hosts: "{{ target }}"
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars:
    redis_bind_interface: "0.0.0.0"
    consul_version: "1.9.0"
    consul_nodes: 
      - "tmt-vm1.7onetella.net"
      - "tmt-vm2.7onetella.net"
      - "tmt-vm3.7onetella.net"    
  roles:
    - consul-agent  
    - geerlingguy.redis
    - redis