---

# -------------------------------------------------------------------------------------
# Golang
# -------------------------------------------------------------------------------------
- name: go
  hosts: nodes 
  become: true
  become_user: root
  become_method: sudo  
  roles:
    - role: uploader
