---

- name: restart consul
  service:
    name: consul
    state: restarted

- name: restart consul-mac
  shell: |
    set -e
    sudo launchctl stop io.consul
    sudo launchctl start io.consul
    exit $?