---
# Install Consul

- name: Add Consul group
  group:
    name: consul
    state: present

- name: Add Consul user
  user:
    name: consul
    group: consul
    system: yes
    state: present
    home: /etc/consul.d
    shell: /bin/zsh

- name: Create /etc/consul.d folder
  file:
    path: /etc/consul.d
    state: directory
    owner: consul
    group: consul
    mode: 0755

- name: Create /opt/consul folder
  file:
    path: /opt/consul
    state: directory
    owner: consul
    group: consul
    mode: 0755

- name: Copy consul.hcl to /etc/consul.d/
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0640
  notify: restart consul-mac    

- name: Download Consul
  unarchive:
    src: "{{ download_url }}"
    dest: /usr/local/bin/
    owner: consul
    group: consul
    mode: 0755
    remote_src: yes
  become: yes
  become_user: root
  become_method: sudo       
  when: 
    - skip_download is not defined      

- name: Copy Consul startup script
  copy:
    src: files/consul.sh.darwin
    dest: /usr/local/bin/consul.sh
    owner: consul
    group: consul
    mode: 0755

- name: Copy Consul service script
  copy:
    src: files/io.consul.plist
    dest: /Library/LaunchDaemons/io.consul.plist
    owner: root 
    group: admin
    mode: 0644

- name: Enable Consul service
  shell: |
    set -e
    sudo launchctl load /Library/LaunchDaemons/io.consul
    sudo launchctl start io.consul
    exit $?
