---

- name: Install Packages
  apt: 
    name:
      - uuid
    state: present
    autoclean: yes      

- name: Create /etc/docker/registry/ folder
  file:
    path: /etc/docker/registry/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy config.yml to /etc/docker/registry/
  template:
    src: config.yml.j2
    dest: /etc/docker/registry/config.yml
    owner: root
    group: root
    mode: 0640

- name: Download docker registry binary
  unarchive:
    src: https://github.com/distribution/distribution/releases/download/v{{ version }}/registry_{{ version }}_linux_amd64.tar.gz
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755    
    remote_src: yes

- name: Copy startup script
  copy:
    src: files/registry.sh
    dest: /usr/local/bin/registry.sh
    owner: root
    group: root
    mode: 0755

- name: Copy garbage_collect.sh script
  copy:
    src: files/garbage_collect.sh
    dest: /root/garbage_collect.sh
    owner: root
    group: root
    mode: 0755

- name: Copy service script
  copy:
    src: files/registry.service
    dest: /etc/systemd/system/registry.service
    owner: root
    group: root
    mode: 0644

- name: Enable registry service
  service:
    name: registry
    enabled: yes    

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: registry





