---
# check-redis

- name: Copy check_redis.py 
  copy:
    src: files/check_redis.py
    dest: /usr/local/bin/check_redis.py
    owner: root
    group: root
    mode: 0755

- name: Install Packages
  apt: 
    name:
      - uuid
      - python3-pip
    state: present
    autoclean: yes      
  become: yes
  become_user: root
  become_method: sudo       

- name: pip install redis
  pip:
    name: redis

- name: Copy redis service definition
  copy:
    src: files/redis.tpl
    dest: /etc/consul.d/redis.tpl
    owner: consul
    group: consul
    mode: 0755

- name: Copy Grafana service definition
  copy:
    src: files/register.sh
    dest: /etc/consul.d/register.sh
    owner: consul
    group: consul
    mode: 0755
  become: yes
  become_user: root
  become_method: sudo

- name: Register with Consul
  shell: |
    set -e
    /etc/consul.d/register.sh redis
    exit 0    
  become: yes
  become_user: root
  become_method: sudo

