---
# Install Authp Server

- name: Copy Server binary
  copy:
    src: files/api_linux_amd64
    dest: /root/api_linux_amd64
    owner: root
    group: root
    mode: 0755

- name: Copy Server startup script
  copy:
    src: files/server.sh
    dest: /root/server.sh
    owner: root
    group: root
    mode: 0755

- name: Copy Server service script
  copy:
    src: files/server.service
    dest: /etc/systemd/system/server.service
    owner: root
    group: root
    mode: 0644

- name: Enable Server service
  shell: |
    set -e
    systemctl enable server
    systemctl start server
    exit 0
