---

# -------------------------------------------------------------------------------------
# Consul cluster
# -------------------------------------------------------------------------------------
- name: consul cluster
  hosts: "{{ target_hosts }}"
  user: "{{ ansible_user }}"  
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars: 
    version: "1.9.0"
    nodes: 
      - "{{node1}}"
      - "{{node2}}"
      - "{{node3}}"    
  roles:
    - consul-cluster