---

- name: Install Packages
  apt: 
    name:
      - python3 
      - python3-pip
      - python3-cryptography
      - less
      - libxext6
      - libxrender1
      - libxtst6
      - libfreetype6
      - libxi6
    update_cache: yes      
    state: present
    autoclean: yes      

- name: Update pip
  become: false 
  shell: |
    python3 -m pip install -U pip
    exit 0

- name: Install projector installer
  become: false
  pip: 
    name: projector-installer
    extra_args: --user

- name: Delete projector ide directory
  file:
    state: absent
    path: /home/{{username}}/.projector/configs/{{ config_name }}

- name: Install ide
  become: false   
  shell: |
    export PATH="$HOME/.local/bin:$PATH"            &&  \
    projector ide autoinstall                           \
    --config-name {{ config_name }}                     \
    --ide-name "{{ ide }}"                              \
    --port  {{ port }}                                  \
    --hostname "*"                                  
  register: output3

- name: Capture install output
  debug:
    var: output3.stdout_lines    

- name: Copy .ssh
  copy:
    src: files/.ssh
    dest: /home/{{username}}/.ssh
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0700

- name: Copy sysctl.conf
  copy:
    src: files/sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: Copy service script
  template:
    src: templates/projector.service.j2
    dest: /etc/systemd/system/{{ config_name }}.service
    owner: root
    group: root
    mode: 0644

- name: Enable and start projector service
  service:
    name: "{{ config_name }}"
    state: started
    enabled: yes        
