---
# Install Aminator

- name: Install system packages (apt version)
  apt: 
    name:
      - python
      - python-pip
      - git
    state: present
    autoclean: yes      

- name: Install Ansible, Aminator, Aminator Ansible provisioner
  pip:
    name: 
      - ansible
      - git+https://github.com/7onetella/aminator.git#egg=aminator
      - git+https://github.com/7onetella/ansible-provisioner.git#egg=aminatorplugins-ansible
    state: present

- name: Copy aminator.plugins.provisioner.ansible.yml
  copy:
    src: files/aminator.plugins.provisioner.ansible.yml
    dest: /etc/aminator/plugins/aminator.plugins.provisioner.ansible.yml
    owner: root
    group: root
    mode: 0644

- name: Copy environments.yml
  copy:
    src: files/environments.yml
    dest: /etc/aminator/environments.yml
    owner: root
    group: root
    mode: 0644    

- name: Create playbooks folder
  file:
    path: /var/playbooks
    state: directory
    mode: "a+rwx"    
    group: "{{ playbook_user }}"

- name: Copy aminator image playbooks by git clone
  git:
    repo: 'https://github.com/7onetella/playbooks.git'
    dest: /var/playbooks
  become: yes
  become_user: "{{ playbook_user }}"
      